import test from 'node:test';
import assert from 'node:assert/strict';
import handler from '../api/explain.js';
import {validateInput,validateExplanation} from '../lib/validation.js';
import {demoCode,demoLesson} from '../demo.js';
function res(){return {statusCode:200,headers:{},setHeader(k,v){this.headers[k]=v;},status(n){this.statusCode=n;return this;},json(v){this.body=v;return this;}};}
test('rejects empty, excessive, and invalid-level inputs',()=>{for(const body of [{code:' ',level:'beginner'},{code:'x'.repeat(4001),level:'beginner'},{code:'x',level:'expert'},{code:'x\n'.repeat(101),level:'beginner'},null])assert.throws(()=>validateInput(body));assert.equal(validateInput({code:'a\r\nb',level:'advanced'}).code,'a\nb');});
test('all demo levels match schema and original source',()=>{for(const level of ['beginner','intermediate','advanced']){const data=validateExplanation(demoLesson(level),demoCode);assert.equal(data.lines.length,8);assert.equal(data.quiz.length,3);}});
test('model validation rejects omissions, duplicate lines and bad quiz answers',()=>{const missing=demoLesson('beginner');missing.lines.pop();assert.throws(()=>validateExplanation(missing,demoCode));const bad=demoLesson('beginner');bad.quiz[0].answer=4;assert.throws(()=>validateExplanation(bad,demoCode));const duplicate=demoLesson('beginner');duplicate.lines[1].number=1;assert.throws(()=>validateExplanation(duplicate,demoCode));const altered=demoLesson('beginner');altered.lines[0].code='invented code';assert.equal(validateExplanation(altered,demoCode).lines[0].code,demoCode.split('\n')[0]);});
test('API rejects method, cross-origin, invalid input and missing config',async()=>{const env=process.env.GEMINI_API_KEY;delete process.env.GEMINI_API_KEY;try{for(const [req,status] of [[{method:'GET',headers:{}},405],[{method:'POST',headers:{origin:'https://other.test',host:'app.test'},body:{code:'x',level:'beginner'}},403],[{method:'POST',headers:{},body:{}},400],[{method:'POST',headers:{},body:{code:'x',level:'beginner'}},503]]){const response=res();await handler(req,response);assert.equal(response.statusCode,status);}}finally{if(env)process.env.GEMINI_API_KEY=env;}});
test('provider success is validated, cached and rate-limited without leaking secrets',async()=>{const originalFetch=globalThis.fetch,env=process.env.GEMINI_API_KEY;process.env.GEMINI_API_KEY='test-only-placeholder';let calls=0;globalThis.fetch=async(url,options)=>{calls++;assert.equal(options.headers['x-goog-api-key'],'test-only-placeholder');return {ok:true,json:async()=>({candidates:[{content:{parts:[{text:JSON.stringify(demoLesson('beginner'))}]}}]})};};try{const req={method:'POST',headers:{'x-real-ip':'test-success'},body:{code:demoCode,level:'beginner'}};const first=res();await handler(req,first);assert.equal(first.statusCode,200);assert.equal(first.body.mode,'ai');const second=res();await handler(req,second);assert.equal(second.body.cached,true);assert.equal(calls,1);for(let i=0;i<3;i++)await handler(req,res());const last=res();await handler(req,last);assert.equal(last.statusCode,429);assert.equal(JSON.stringify(first.body).includes('test-only-placeholder'),false);}finally{globalThis.fetch=originalFetch;if(env)process.env.GEMINI_API_KEY=env;else delete process.env.GEMINI_API_KEY;}});
test('provider errors and malformed JSON fail safely without retrying',async()=>{const originalFetch=globalThis.fetch,env=process.env.GEMINI_API_KEY;process.env.GEMINI_API_KEY='test-only-placeholder';try{globalThis.fetch=async()=>({ok:false,status:429});let response=res();await handler({method:'POST',headers:{'x-real-ip':'test-error'},body:{code:'bad()',level:'intermediate'}},response);assert.equal(response.statusCode,429);globalThis.fetch=async()=>({ok:true,json:async()=>({candidates:[{content:{parts:[{text:'not json'}]}}]})});response=res();await handler({method:'POST',headers:{'x-real-ip':'test-malformed'},body:{code:'bad()',level:'advanced'}},response);assert.equal(response.statusCode,502);assert.ok(!JSON.stringify(response.body).includes('test-only-placeholder'));}finally{globalThis.fetch=originalFetch;if(env)process.env.GEMINI_API_KEY=env;else delete process.env.GEMINI_API_KEY;}});
