import {demoCode,demoLesson} from './demo.js';
const $=id=>document.getElementById(id);
let lesson=null, answered=new Map(), controller=null, revision=0;
function node(tag,text,cls){const el=document.createElement(tag);if(text!==undefined)el.textContent=text;if(cls)el.className=cls;return el;}
function count(){ $('count').textContent=`${$('code').value.length.toLocaleString()} / 4,000 characters`;if(!$('code-preview').hidden)preview();}
function preview(){const el=$('code-preview').querySelector('code');el.textContent=$('code').value;el.className=$('language').value==='auto'?'':`language-${$('language').value}`;delete el.dataset.highlighted;if(window.hljs)window.hljs.highlightElement(el);}
function error(message){$('error').textContent=message;$('error').hidden=!message;}
function mode(){const demo=$('demo').checked;$('demo-notice').hidden=!demo;$('explain').children[1]?.remove();$('explain').replaceChildren(node('span','✧'),document.createTextNode(demo?'Explore demo lesson':'Explain my code'),node('span','→'));if(demo){$('code').value=demoCode;$('language').value='javascript';count();}reset();}
function reset(){revision++;if(controller)controller.abort();controller=null;lesson=null;answered.clear();$('result').hidden=true;$('empty').hidden=false;$('loading').hidden=true;$('result-badge').textContent='Your learning space';$('explain').disabled=false;error('');}
function tab(name){for(const b of document.querySelectorAll('[data-tab]'))b.setAttribute('aria-pressed',String(b.dataset.tab===name));for(const id of ['overview','lines','concepts','quiz'])$(id).hidden=id!==name;}
function updateScore(){const total=lesson.quiz.length,done=answered.size,correct=[...answered.entries()].filter(([i,a])=>lesson.quiz[i].answer===a).length;$('quiz-progress').textContent=done?`${done}/${total}`:'';const score=$('quiz-score');score.textContent=done===total?`You scored ${correct} / ${total}. ${correct===total?'Nicely done!':'Review the explanations and try again.'}`:`${done} of ${total} answered`;}
function renderQuiz(){answered.clear();const root=$('quiz');root.replaceChildren(node('h3','Put your understanding to the test'),node('p','Choose one answer per question. You’ll see the explanation immediately.'));const score=node('div','','score');score.id='quiz-score';score.setAttribute('role','status');root.append(score);lesson.quiz.forEach((q,i)=>{const card=node('section',undefined,'quiz-card');card.append(node('h4',`${i+1}. ${q.question}`));q.options.forEach((option,j)=>{const button=node('button',`${String.fromCharCode(65+j)}. ${option}`,'option');button.addEventListener('click',()=>{if(answered.has(i))return;answered.set(i,j);const options=card.querySelectorAll('button');options.forEach((b,k)=>{b.disabled=true;if(k===q.answer)b.classList.add('correct');else if(k===j)b.classList.add('wrong');});const feedback=node('p',`${j===q.answer?'Correct!':'Not quite.'} ${q.explanation}`,'feedback');feedback.setAttribute('role','status');card.append(feedback);updateScore();});card.append(button);});root.append(card);});const retry=node('button','↻ Try quiz again','quiet');retry.addEventListener('click',renderQuiz);root.append(retry);updateScore();}
function render(){ $('overview').replaceChildren(node('h3','The big picture'),node('p',lesson.summary));const callout=node('div',undefined,'callout');callout.append(node('p',`Your ${lesson.level} lesson includes ${lesson.lines.length} explained lines, ${lesson.concepts.length} concepts, and ${lesson.quiz.length} quiz questions.`));$('overview').append(callout);$('lines').replaceChildren(node('h3','One line at a time'));for(const l of lesson.lines){const card=node('article',undefined,'line-card');card.append(node('span',`LINE ${l.number}`,'line-number'),node('code',l.code),node('p',l.explanation));$('lines').append(card);}$('concepts').replaceChildren(node('h3','Ideas to take with you'));for(const c of lesson.concepts){const card=node('article',undefined,'concept-card');card.append(node('h4',c.name),node('p',c.explanation));$('concepts').append(card);}renderQuiz();tab('overview');$('result-badge').textContent=lesson.mode==='demo'?'Prepared demo':'Gemini explanation';$('empty').hidden=true;$('loading').hidden=true;$('result').hidden=false;}
async function explain(){error('');const code=$('code').value,level=document.querySelector('[name=level]:checked').value;if(!code.trim())return error('Paste some code or load an example first.');if(code.length>4000||code.split('\n').length>100)return error('Use a snippet under 4,000 characters and 100 lines.');if($('demo').checked){if(code!==demoCode)return error('Demo mode only supports the fixed sample. Load the example or turn off Demo mode for your own code.');lesson={...demoLesson(level),code,level};render();return;}
 const current=++revision;controller=new AbortController();const timeout=setTimeout(()=>controller?.abort(),50000);$('explain').disabled=true;$('empty').hidden=true;$('result').hidden=true;$('loading').hidden=false;
 try{const response=await fetch('/api/explain',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code,level}),signal:controller.signal});const data=await response.json();if(!response.ok)throw new Error(data.error||'Could not explain your code. Please try again.');if(current!==revision)return;lesson={...data,code,level};render();}catch(e){if(current!==revision)return;$('loading').hidden=true;$('empty').hidden=false;error(e.name==='AbortError'?'Request cancelled or timed out. Try a shorter snippet or Demo mode.':e.message);}finally{clearTimeout(timeout);if(current===revision){$('explain').disabled=false;controller=null;}}
}
$('code').addEventListener('input',()=>{reset();count();});$('language').addEventListener('change',preview);document.querySelectorAll('[name=level]').forEach(el=>el.addEventListener('change',reset));$('demo').addEventListener('change',mode);$('load-example').addEventListener('click',()=>{reset();$('code').value=demoCode;$('language').value='javascript';count();});$('demo-top').addEventListener('click',()=>{$('demo').checked=true;mode();explain();$('input-title').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});});$('preview-toggle').addEventListener('click',()=>{$('code-preview').hidden=!$('code-preview').hidden;$('preview-toggle').setAttribute('aria-expanded',String(!$('code-preview').hidden));preview();});$('explain').addEventListener('click',explain);$('cancel').addEventListener('click',reset);document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>tab(b.dataset.tab)));$('code').addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter'){e.preventDefault();if(!$('explain').disabled)explain();}});
$('download').addEventListener('click',()=>{if(!lesson)return;const text=`# Code Explainer AI lesson\n\nMode: ${lesson.mode}\nLevel: ${lesson.level}\n\n## Summary\n${lesson.summary}\n\n## Line explanations\n${lesson.lines.map(l=>`Line ${l.number}: ${l.code}\n${l.explanation}`).join('\n\n')}\n\n## Concepts\n${lesson.concepts.map(c=>`${c.name}: ${c.explanation}`).join('\n\n')}\n\n## Quiz\n${lesson.quiz.map((q,i)=>`${i+1}. ${q.question}\n${q.options.map((o,j)=>`${String.fromCharCode(65+j)}. ${o}`).join('\n')}\nAnswer: ${String.fromCharCode(65+q.answer)}. ${q.explanation}`).join('\n\n')}`;const url=URL.createObjectURL(new Blob([text],{type:'text/plain'}));const a=node('a');a.href=url;a.download='code-lesson.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});count();
