import test,{afterEach} from 'node:test';
import assert from 'node:assert/strict';
import handler,{resetLimits} from '../api/explain.js';
import {samples,demoResult} from '../lib/samples.js';
import {validateInput,validateResult} from '../lib/validation.js';
const originalFetch=globalThis.fetch, originalKey=process.env.GEMINI_API_KEY;
afterEach(()=>{globalThis.fetch=originalFetch;if(originalKey===undefined)delete process.env.GEMINI_API_KEY;else process.env.GEMINI_API_KEY=originalKey;delete process.env.APP_ACCESS_CODE;resetLimits();});
async function request(body={},options={}){const req={method:'POST',body,headers:{host:'localhost',...options.headers},...options};let status=200,output;const res={setHeader(){},status(value){status=value;return this;},json(value){output=value;}};await handler(req,res);return {status,body:output};}
const input=()=>({code:samples[0].code,level:'beginner',language:'Python',mode:'live'});
function providerResponse(){const data=demoResult(samples[0],'beginner');return {ok:true,json:async()=>({candidates:[{finishReason:'STOP',content:{parts:[{text:JSON.stringify(data)}]}}]})};}
test('all five curated demos work without an API call',async()=>{globalThis.fetch=()=>{throw new Error('unexpected fetch');};for(const sample of samples){const response=await request({code:sample.code,level:'advanced',language:sample.language,mode:'demo'});assert.equal(response.status,200);assert.equal(response.body.mode,'demo');assert.equal(response.body.lines.length,sample.code.split('\n').length);validateResult(response.body,sample.code);}});
test('reject empty, oversized, excessive lines and invalid level inputs',()=>{for(const body of [{...input(),code:''},{...input(),code:'x'.repeat(4001)},{...input(),code:'x\n'.repeat(81)},{...input(),level:'expert'}])assert.throws(()=>validateInput(body));});
test('demo never pretends to explain custom code',async()=>{assert.equal((await request({...input(),mode:'demo',code:'unknown()'})).status,400);});
test('GET and foreign origins are rejected',async()=>{assert.equal((await request(input(),{method:'GET'})).status,405);assert.equal((await request(input(),{headers:{host:'localhost',origin:'https://foreign.example'}})).status,403);});
test('missing key has a clear configuration error',async()=>{delete process.env.GEMINI_API_KEY;assert.equal((await request(input())).status,503);});
test('optional access code protects live AI but leaves demos accessible',async()=>{process.env.GEMINI_API_KEY='test-only';process.env.APP_ACCESS_CODE='test-access';assert.equal((await request(input())).status,401);assert.equal((await request({...input(),mode:'demo'})).status,200);globalThis.fetch=async()=>providerResponse();assert.equal((await request(input(),{headers:{host:'localhost','x-access-code':'test-access'}})).status,200);});
test('live results use original code lines, are validated and cached',async()=>{process.env.GEMINI_API_KEY='test-only';let calls=0;globalThis.fetch=async()=>{calls++;return providerResponse();};const a=await request(input()),b=await request(input());assert.equal(a.status,200);assert.equal(a.body.mode,'live');assert.equal(a.body.lines[0].code,samples[0].code.split('\n')[0]);assert.equal(b.body.cached,true);assert.equal(calls,1);});
test('rate limit blocks fourth live request',async()=>{process.env.GEMINI_API_KEY='test-only';globalThis.fetch=async()=>providerResponse();for(let i=0;i<3;i++)assert.equal((await request(input())).status,200);assert.equal((await request(input())).status,429);});
test('provider errors never expose credentials or raw messages',async()=>{process.env.GEMINI_API_KEY='secret-test-value';globalThis.fetch=async()=>({ok:false,status:403,json:async()=>({error:'secret-test-value'})});const response=await request(input());assert.equal(response.status,503);assert.ok(!JSON.stringify(response).includes('secret-test-value'));});
test('quota exhaustion and truncated output are handled explicitly',async()=>{process.env.GEMINI_API_KEY='test-only';globalThis.fetch=async()=>({ok:false,status:429});assert.equal((await request(input())).status,429);resetLimits();globalThis.fetch=async()=>({ok:true,json:async()=>({candidates:[{finishReason:'MAX_TOKENS'}]})});assert.equal((await request(input())).status,502);});
test('malformed quiz answers and missing lines are rejected',()=>{const result=demoResult(samples[0],'beginner');result.quiz[0].answer=6;assert.throws(()=>validateResult(result,samples[0].code));const other=demoResult(samples[0],'beginner');other.lines.pop();assert.throws(()=>validateResult(other,samples[0].code));});
